### ISSUE TITLE
File > Export plugins... not showing up

### ISSUE THREAD

**Issue by jDally987** [shiraji/plugin-importer-exporter#7]
I'm not seeing the option in the File menu anywhere. Using Webstorm 192.5118.44 (June 14, 2019 build) the EAP version.

**Comment by juliangut** [comment]
Same here, PhpStorm 2019.2 - 192.5728.108, built on July 24, 2019

**Comment by shiraji** [comment]
Let me check!

**Comment by shiraji** [comment]
Does this still happen? I'm not able to reproduce this in 2019.2 IntelliJ IDEA. 

```
IntelliJ IDEA 2019.2.1 (Ultimate Edition)
Build #IU-192.6262.58, built on August 20, 2019
```

**Comment by stepanselyuk** [comment]
```
PhpStorm 2019.2.4
Build #PS-192.7142.41, built on October 30, 2019
Runtime version: 11-internal+125 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
```

Same, no option in the File menu.

**Comment by juliangut** [comment]
Tried just now

> 11/12/19 3:08 PM	Plugin Error: Plugin "Plugin Importer+Exporter" defines no module dependencies (supported only in IntelliJ IDEA).

```
PhpStorm 2019.3 EAP
Build #PS-193.4932.16, built on October 31, 2019
Runtime version: 11.0.4+10-b520.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.18-200.fc30.x86_64
```

**Comment by shiraji** [comment]
Thanks for the info @stepanselyuk @juliangut

**Comment by juliangut** [comment]
The problem persists with latest RC

> 11/22/19 10:21 AM	Plugin Error: Plugin "Plugin Importer+Exporter" defines no module dependencies (supported only in IntelliJ IDEA).

```
PhpStorm 2019.3
Build #PS-193.5233.64, built on November 21, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.18-200.fc30.x86_64
```

Any luck on having an update?

**Comment by shiraji** [comment]
I couldn't compile this project because this was really old. Now, I migrated to gradle project and start looking at the problem.

It seems 2018.1 works fine, so I believe this problem is some kinda of new setting that is introduced in 192 or higher. Let me check that.

**Comment by shiraji** [comment]
Guys, I think v0.0.3 fix this problem. Please reopen this issue if the problem persists.

**Comment by juliangut** [comment]
I've just tested and it works, thanks a lot

**Comment by stepanselyuk** [comment]
Just installed the plugin on:
```
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021

Runtime version: 11.0.10+9-b1341.45 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Non-Bundled Plugins: YAML/Ansible support (0.11.2), com.github.shiraji.pluginimporterexporter (0.0.3), com.github.timo_reymann.ansible_vault_integration (1.2.1), ir.msdehghan.plugins.ansible (0.92), ru.sadv1r.ansible-vault-editor-idea-plugin (1.11)
Kotlin: 211-1.4.32-release-IJ7142.27
```

And the plugin not showing in the File menu.
